### ISSUE TITLE
A little typo

### ISSUE THREAD

**Issue by conleym** [a3ammar/emacs.d#1]
Hi!

Just scrolling through looking for ideas and noticed that you have a typo. In this snippet

```
(setq kill-buffer-query-functions
      (remq 'proccess-kill-buffer-query-function
            kill-buffer-query-functions))
```

You have `proccess` when it should just be `process`. Figured I'd save you the trouble of hunting it down yourself.

**Comment by a3ammar** [comment]
Thanks!
I'm kind of delighted that you found something useful.
